sudo: false
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER_NAME=gcc CXX=g++-6
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
    - os: osx
      compiler: clang

install:
  - if [ "$CXX" = "g++" ]; then 
      export CXX="g++-6";
    fi

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake || brew install cmake
    fi
  - cmake --version

before_script:
  - mkdir build
  - cd build
  - cmake ..
script: 
  - make 
  - ./test_runner
