sudo: required
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER_NAME=gcc CXX=g++-6
      addons:
        apt:
          packages:
            - g++-6
            - cmake
            - cmake-data
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
    - os: osx
      compiler: clang
      addons:
        apt:
          packages:
            - cmake
            - cmake-data
          sources:
            - george-edison55-precise-backports

install:
  - if [ "$CXX" = "g++" ]; then 
      export CXX="g++-6";
    fi

  ########################################################
  # install Qt files
  ########################################################
  install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         sudo apt-add-repository -y ppa:beineri/opt-qt541
      && sudo apt-get -qq update
      && sudo apt-get -qq install qt54tools qt54svg qt54webkit
      ;
    else
         brew update
      && brew install qt5
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

before_script:
  - mkdir build
  - cd build
  - cmake ..
script: 
  - make 
  - ./test_runner
