language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER_NAME=gcc CXX=g++-6 QT_BASE=56
      addons:
        apt:
          packages:
            - g++-6
            - cmake
            - cmake-data
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            
before_install:
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
      sudo apt-get update -qq;
    else
      brew update;
    fi
install:
  - if [ "$CXX" = "g++" ]; then 
      export CXX="g++-6";
    fi
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..
script: 
  - make 
  - ./test_runner
