sudo: required
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      env: COMPILER_NAME=gcc CXX=g++-6
      addons:
        apt:
          packages:
            - g++-6
            - cmake
            - cmake-data
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
    - os: osx
      compiler: clang
      addons:
        apt:
          packages:
            - cmake
            - cmake-data
          sources:
            - george-edison55-precise-backports

install:
  - if [ "$CXX" = "g++" ]; then 
      export CXX="g++-6";
    fi

  ########################################################
  # install Qt files
  ########################################################
  - sudo apt-get install -y qt5-default qttools5-dev-tools

before_script:
  - mkdir build
  - cd build
  - cmake ..
script: 
  - make 
  - ./test_runner
